#!/bin/bash

# This script covers 
    # 1. Reclassifing with MIDAS 5 taxonomy
    # 2. Classifing gut database with MIDAS tax
    # 3. Finding the multiple species matches hits

# Moduels
module load seqtk

# Varibles
TAXDB=/space/databases/midas/MiDAS5.2_20231221/output/FLASVs_w_sintax.fa
ASVs_to_be_classified=data/ASVs.R1.fa
output_path=output/classification_MIDAS_5.2

# Classification using usearch
usearch -sintax $ASVs_to_be_classified -db "$TAXDB" -tabbedout $output_path/ASVs.R1.sintax_0.6 -strand both -sintax_cutoff 0.6 -threads 10 -quiet
    sort -V $output_path/ASVs.R1.sintax_0.6 -o $output_path/ASVs.R1.sintax_0.6


# Finding the unclassified species
grep -vE '^.*,[^,]*,s:.*,[^,]*,s:|^.*,[^,]*,s:.*,s:.*,' $output_path/ASVs.R1.sintax_0.6 > $output_path/ASVs.R1.sintax_0.6_unclassified_species

# Count number of unclassifed ASVs by each method
wc -l $output_path/ASVs.R1.sintax_0.6_unclassified_species
wc -l $output_path/ASVs.R1.sintax_unclassified_species


# Classify gut bacteria
    ## HitDB
    HitDB=data/Gut_databases/16S_sequences/HITdb_sequences.fna
    results=output/classification_MIDAS_5.2/gut_DB_classification/gut_matches_HitDB.txt
    usearch -usearch_global $HitDB -db $TAXDB -id 0.987 -blast6out $results -maxaccepts 50 -strand both #-query_cov 1.0 -maxaccepts 50
    ## HRMG
    HRMG=data/Gut_databases/16S_sequences/HRMG_16S_rRNA_library.fasta
    results=output/classification_MIDAS_5.2/gut_DB_classification/gut_matches_HRMG.txt
    usearch -usearch_global $HRMG -db $TAXDB -id 0.987 -blast6out $results -maxaccepts 50 -strand both #-strand plus -query_cov 1.0 -maxaccepts 50


# Investigate unclassified
    ## Filter .fa file to only include unclassified ASV
    ASV_vector="$output_path/unclassified_ASVs/ASV_names_0.6.txt"
    cut -f1 "$output_path/ASVs.R1.sintax_0.6_unclassified_species" > $ASV_vector
    unclassified_ASV_fasta="output/classification_MIDAS_5.2/unclassified_ASVs/unclassified_ASVs_0.6.fasta"    
    ## Subset sequences 
    seqtk subseq $ASVs_to_be_classified $ASV_vector > $unclassified_ASV_fasta
    ## Use useach for finding all species hits in the database
    results="$output_path/unclassified_ASVs/useach_ASVs_unclassified_0.6.m8"
    usearch -usearch_global $unclassified_ASV_fasta -db $TAXDB -id 0.987 -blast6out $results -strand plus -query_cov 1.0 -maxaccepts 1000


